image: continuumio/miniconda:latest

stages:
  - build
  - test

build-environment:
    stage: build
    script:
        - cat environment.yml
        - conda env create -f environment.yml
        - source activate redpy
        - pip install -e .
        - echo 'Installed REDPy...'
        - redpy-initialize -v

coverage-test-job:
    stage: test
    script:
        - pip install coverage pytest
        - coverage -m pytest
        - coverage report
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

lint-test-job:
    stage: test
    script:
        - pip install pycodestyle pydocstyle pylint
        - pycodestyle redpy
        - pydocstyle redpy
        - pylint redpy