image: continuumio/miniconda:latest

stages:
  - build
  - test

build-environment:
    stage: build
    script:
        - conda env create -f environment.yml
        - conda activate redpy
        - pip install pycodestyle pydocstyle pylint
        - pip install coverage pytest
        - pip install .
    after_script:
        - conda deactivate

coverage-test-job:
    stage: test
    before_script:
        - conda activate redpy
    script:
        - coverage -m pytest
        - coverage report
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    after_script:
        - conda deactivate

lint-test-job:
    stage: test
    before_script:
        - conda activate redpy
    script:
        - pycodestyle redpy
        - pydocstyle redpy
        - pylint redpy
    after_script:
        - conda deactivate